FROM ubuntu:latest

ENV PROJECT_PATH=/loramac-node
RUN mkdir -p $PROJECT_PATH

RUN apt-get update && \
	apt-get install -y \
	build-essential \
	cmake \
	cmake-curses-gui \
	gcc-arm-none-eabi

WORKDIR $PROJECT_PATH
